#
# SE Mod Builder global configuration file
#

# All default paths will be checked for dependencies.
# If one of these isn't available in a default path, provide it below.

# git_exe_path: 'C:\some\path\to\git.exe'
# mwm_exe_path: 'C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Tools\MwmBuilder\MwmBuilder.exe'
# se_data_dir: 'C:\Users\UserName\AppData\Roaming\SpaceEngineers'
# se_exe_path: 'C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Bin\x64\SpaceEngineers.exe'
# se_mods_dir: 'C:\Users\UserName\AppData\Roaming\SpaceEngineers\Mods'
# se_steam_dir: 'C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers'
# sepl_exe_path: 'C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\LoadARMS.exe'
